apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: dscoletor
    access: proxy
    url: http://prometheus:9090/coletor
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      manageAlerts: false
