global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - rules/*.yml

scrape_configs:
  - job_name: 'prometheus'
    # Se for publicar atrás de proxy via subpath 
    metrics_path: /coletor/metrics
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Docker Engine metrics (opcional, se habilitar no daemon.json)
  - job_name: 'docker'
    static_configs:
      - targets: ['172.17.0.1:9323']
    # /etc/docker/daemon.json
    # {
    #   "metrics-addr": "0.0.0.0:9323"
    # }
    # Dica: por segurança prefira "127.0.0.1:9323" e colete via host-gateway,
    # adicionando um endpoint do node-exporter textfile ou um socat local.

  - job_name: 'apcupsd'
    static_configs:
      - targets: ['172.17.0.1:9162']

  - job_name: 'dcgm-exporter'
    static_configs:
      - targets: ['dcgm-exporter:9400']
    metrics_path: /metrics
    scrape_timeout: 10s

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
