# Use root/example as user/password credentials
# mongodb://root:example@localhost:27017
services:

  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    restart: always
    ports:
        - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: jquest
    volumes:
      - mongo-data:/data/db
    networks:
      - proxy-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 88:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: marquezjp
      ME_CONFIG_BASICAUTH_PASSWORD: jquest
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: jquest
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    links:
      - mongo
    networks:
      - proxy-network

volumes:
  mongo-data:

networks:
 proxy-network:
   external: true
