version: '3.3'

services:
  db:
    image: mysql
    container_name: MySQL
    hostname: dbserver
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=MySQL2023
      - MYSQL_DATABASE=mydb
    volumes:
      - P:\DBServer\MySQL\Dados:/var/lib/mysql
    networks:
      - db-network

  myadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 88:80
    environment:
      - PMA_HOST=db:3306
      - MYSQL_ROOT_PASSWORD=MySQL2023
    depends_on:
      - db
    networks:
      - db-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
