global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

#  - job_name: 'apcupsd'
#    static_configs:
#      - targets: ['apcupsd:9162']
      
#  - job_name: 'dcgm-exporter'
#    static_configs:
#      - targets: ['dcgm-exporter:9400']
#    metrics_path: /metrics
#    scrape_timeout: 10s
