version: '3.1'

services:

  db:
    image: redis
    restart: always
    command: redis-server --requirepass Redis2020
    ports:
        - "6379:6379"
    volumes:
        - J:\DBServer\Redis\Dados:/var/lib/redis

