services:
  segaddb:
    image: mcr.microsoft.com/mssql/server
    container_name: segaddb
    hostname: segaddb
    restart: always
    environment:
      - MSSQL_SA_PASSWORD=jquest
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - /var/lib/docker/volumes/segad-data/SEGADDB/Dados:/var/opt/mssql/data
      - /var/lib/docker/volumes/segad-data/SEGADDB/Log:/var/opt/mssql/log
      - /var/lib/docker/volumes/segad-data/SEGADDB/Secrets:/var/opt/mssql/secrets
      - /var/lib/docker/volumes/segad-data/SEGADDB/Dumps:/var/opt/mssql/dumps
    networks:
      - proxy-network

networks:
 proxy-network:
   external: true