services:
  sigrhdb:
    image: container-registry.oracle.com/database/enterprise
    container_name: Oracle
    hostname: dbserver
    restart: always
    ports:
      - 1521:1521
      - 8080:8080
      - 5500:5500
    environment:
      - ORACLE_PWD=Oracle2023
      - ORACLE_SID=SIGRH
      - ORACLE_PDB=SIGRHDB1
    volumes:
      - /var/lib/docker/volumes/sigrh-data/SIGRH-RR:/opt/oracle/oradata
      - /var/lib/docker/volumes/sigrh-data/SIGRH-RR/DUMP:/opt/oracle/oradata/datapump
