services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      # Evite deixar desativada a sanitização de HTML a menos que precise MESMO
      - GF_SECURITY_ADMIN_USER=marquezjp
      - GF_SECURITY_ADMIN_PASSWORD=jquest
      - GF_USERS_ALLOW_SIGN_UP=false
      # Se for publicar atrás de proxy, descomente e ajuste:
      # - GF_SERVER_ROOT_URL=https://grafana.mrqz.me
      # - GF_SERVER_DOMAIN=grafana.mrqz.me
    volumes:
      # Provisioning opcional (datasources/dashboards/alerts-as-code)
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana-data:/var/lib/grafana
    networks:
      - proxy-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9091:9090"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9090/-/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--log.level=warn'
      - '--storage.tsdb.path=/prometheus'
      # Retenção mais segura para não crescer infinito (ajuste conforme disco)
      - '--storage.tsdb.retention.time=30d'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    networks:
      - proxy-network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - proxy-network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    command:
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.processes'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.filesystem.ignored-fs-types=^(autofs|proc|sysfs|cgroup.*|overlay|squashfs|tmpfs|devtmpfs|nsfs|tracefs)$$'
      - '--no-collector.ipvs'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - proxy-network

# Exporta /metrics do apcupsd (rodando no host)
  apcupsd:
    image: jangrewe/apcupsd-exporter:latest
    container_name: apcupsd
    restart: unless-stopped
    network_mode: "host"

  dcgm-exporter:
    image: nvidia/dcgm-exporter:4.4.0-4.5.0-ubuntu22.04
    container_name: dcgm-exporter
    hostname: dcgm-exporter
    restart: unless-stopped
    runtime: nvidia
    deploy:
        resources:
          reservations:
            devices:
              - capabilities: [gpu]
    cap_add:
      - SYS_ADMIN
    ports:
      - "9400:9400"
    environment:
      - DCGM_EXPORTER_LISTEN=0.0.0.0:9400
      - DCGM_EXPORTER_KUBERNETES=false
    networks:
      - proxy-network

volumes:
  prometheus-data:
  grafana-data:

networks:
  proxy-network:
    external: true
