services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx:/etc/nginx
      - ./cert:/cert
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
