services:
  oracle:
    image: container-registry.oracle.com/database/enterprise
    container_name: oracle
    hostname: oracle
    restart: always
    ports:
      - 1521:1521
      - 8080:8080
      - 5500:5500
    environment:
      - ORACLE_PWD=jquest
      - ORACLE_SID=JOTAPE
      - ORACLE_PDB=JOTAPEDB
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - proxy-network

volumes:
  oracle-data:

networks:
 proxy-network:
   external: true