services:
  ollama:
    build: .
    container_name: ollama-deepseek
    restart: unless-stopped
    runtime: nvidia
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - proxy-network

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    restart: unless-stopped
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
      - DEFAULT_MODELS=llama3
    depends_on:
      - ollama
    volumes:
      - openwebui_data:/app/backend/data
    networks:
      - proxy-network

volumes:
  ollama-data:
  openwebui_data:

networks:
 proxy-network:
   external: true
