services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    runtime: nvidia
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    networks:
      - proxy-network

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
      - DEFAULT_MODELS=llama3
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - proxy-network

volumes:
  ollama-data:

networks:
 proxy-network:
   external: true
