groups:
  - name: docker-alerts
    rules:
      - alert: ContainerHighCPU
        expr: sum by (instance, name) (rate(container_cpu_usage_seconds_total{image!=""}[5m])) > 0.8
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "CPU alta no contêiner ({{ $labels.name }})"
          description: "Uso de CPU > 0.8 core por 10m no contêiner {{ $labels.name }}."

      - alert: ContainerHighMemory
        expr: (container_memory_working_set_bytes{image!=""} / container_spec_memory_limit_bytes{image!=""}) > 0.90 and on (instance,name) container_spec_memory_limit_bytes{image!=""} > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Memória alta no contêiner ({{ $labels.name }})"
          description: "Contêiner {{ $labels.name }} usando >90% do limite por 5m."

      - alert: ContainerRestartingFrequently
        expr: increase(container_restart_count_total[10m]) > 3
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "Reinícios frequentes ({{ $labels.name }})"
          description: "Contêiner {{ $labels.name }} reiniciou >3x nos últimos 10m. Verifique logs."
