groups:
  - name: prometheus-alerts
    rules:
      # 1) Falhas ao avaliar regras
      - alert: PrometheusRuleEvaluationFailures
        expr: increase(prometheus_rule_evaluation_failures_total[5m]) > 0
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "Falhas ao avaliar regras no Prometheus"
          description: "Houve falha(s) na avaliação de regras nos últimos 5m. Verifique logs/configuração."

      # 2) Target(s) do Prometheus indisponível(veis)
      - alert: PrometheusTargetMissing
        expr: up == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Target indisponível ({{ $labels.job }})"
          description: "O target {{ $labels.instance }} do job {{ $labels.job }} está DOWN há >5m."

      # 3) Séries temporais demais (pressão de memória)
      - alert: PrometheusHighSeriesCount
        expr: prometheus_tsdb_head_series > 1e6
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Número elevado de séries no Prometheus"
          description: "Mais de 1M de séries em memória por >10m. Verifique jobs/labels."

      # 4) Scrapes lentos (pode indicar gargalo)
      - alert: PrometheusScrapeSlow
        expr: histogram_quantile(0.90, sum by (job, le) (rate(scrape_duration_seconds_bucket[5m]))) > max by (job) (scrape_timeout_seconds) * 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Scrape lento do Prometheus"
          description: "90% dos scrapes do job {{ $labels.job }} levam >10s por 5m."
