services:
 postgres:
   image: postgres:latest
   container_name: postgres
   restart: unless-stopped
   environment:
     - POSTGRES_USER=jotape
     - POSTGRES_PASSWORD=jquest
     - POSTGRES_DB=postgres_db
     - VIRTUAL_HOST=postgres.mrqz.me
     - VIRTUAL_PORT=5432
     - LETSENCRYPT_HOST=postgres.mrqz.me
     - LETSENCRYPT_EMAIL=joaopaulo.marquez@gmail.com
   ports:
     - 5432:5432
   volumes:
     - postgres-data:/var/lib/postgresql/data
   networks:
     - proxy-network

networks:
  proxy-network:
    external: true

volumes:
  postgres-data:
