services:
  sigrhdb:
    image: container-registry.oracle.com/database/enterprise
    container_name: sigrhdb
    hostname: sigrhdb
    restart: always
    ports:
      - 1522:1521    # SQL*Net
      - 3130:8080    # APEX/EM Express
      - 5501:5500    # EM Express (HTTPS)
    environment:
      - ORACLE_PWD=jquest
      - ORACLE_SID=SIGRH
      - ORACLE_PDB=SIGRHDB1
    volumes:
      - /var/lib/docker/DBSERVER/SIGRH-RR:/opt/oracle/oradata
      - /var/lib/docker/DBSERVER/SIGRH-RR/DUMP:/opt/oracle/oradata/datapump
    shm_size: "4g"    # Aumenta memória compartilhada
    mem_limit: "32g"  # Limita memória do contêiner
    cpus: "6.0"       # Limita número de CPUs
    sysctls:
      kernel.sem: "250 32000 100 128"
    networks:
      - proxy-network

networks:
 proxy-network:
   external: true