{
 "title": "APC UPS",
 "description": "APS UPS monitoring with Prometheus and apcupsd exporter",
 "tags": [ "apcupsd" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Current Time On Battery",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apcupsd_battery_time_left_seconds"
    }
   ]
  },
  {
   "title": "Current Load",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "apcupsd_ups_load_percent" }
   ]
  },
  {
   "title": "Battery Time Left",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "apcupsd_battery_time_left_seconds",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Battery Charge Percent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "apcupsd_battery_charge_percent", "legendFormat": "{{model}}" }
   ]
  },
  {
   "title": "UPS Load Percentage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "apcupsd_ups_load_percent", "legendFormat": "{{model}}" }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "apcupsd_battery_nominal_volts", "legendFormat": "nominal" },
    { "expr": "apcupsd_battery_volts", "legendFormat": "actual" }
   ]
  },
  {
   "title": "AC Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "apcupsd_line_nominal_volts", "legendFormat": "nominal" },
    { "expr": "apcupsd_line_volts", "legendFormat": "actual" }
   ]
  }
 ]
}