{
 "title": "Docker Engine Metrics - MRQZ",
 "description": "Draw some docker metrics",
 "tags": [
  "Docker",
  "Docker Metrics",
  "Docker Engine",
  "Prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "container_name",
    "label": "Container",
    "query": {
     "query": "label_values(container_memory_usage_bytes{image!=\"\",name!=\"\"}, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Server", "type": "row", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "CPU (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Memória",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)"
    }
   ]
  },
  {
   "title": "Disco Raiz",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\"} * 100)/node_filesystem_size_bytes{mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "Disco Docker",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/var/lib/docker\"} * 100)/node_filesystem_size_bytes{mountpoint=\"/var/lib/docker\"})"
    }
   ]
  },
  {
   "title": "Tráfego de Rede Recebido [B/s, 5m média]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytespersecond" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lo|veth.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Tráfego de Rede Enviado [B/s, 5m média]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytespersecond" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"lo|veth.*\"}[5m]))"
    }
   ]
  },
  { "title": "CPU Containers", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"$container_name\",name=~\".+\"}[5m])) by (name) *100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Memória Containers", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Memória Containers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\"$container_name\",name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memória Cached Containers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_cache{name=~\"$container_name\",name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Tráfego de Rede por Containers", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Tráfego de Rede Recebido por Containers [B/s, 5m média]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\"$container_name\",name=~\".+\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Tráfego de Rede Enviado por Containers [B/s, 5m média]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\"$container_name\",name=~\".+\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Informações dos Containers", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Informações dos Containers",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{name=~\".+\"})/86400",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}