services:
  # Reverse proxy NGINX
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/snippets:/etc/nginx/snippets:ro
      - ./certs:/etc/nginx/certs:ro
      - ./html:/var/www/mrqz.me:ro
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true

# Gerar Autoridade Certificadora (CA) e Certificado Digital do Domínio
# chmod +x ~/docker/nginx/certs/gerar-ca-cert.sh
# ~/docker/nginx/certs/gerar-ca-cert.sh -d portainer.mrqz.me
# ~/docker/nginx/certs/gerar-ca-cert.sh -d mrqz.me --wildcard --san "DNS:mrqz.me"
# openssl s_client -connect portainer.mrqz.me:443 -servername portainer.mrqz.me </dev/null 2>/dev/null | openssl x509 -noout -text | grep -E 'Subject:|Issuer:|DNS:'

# Importar CA local no cliente Windows
# Import-Certificate -FilePath "P:\Projetos\JotaPeServer\certs\ca.crt" -CertStoreLocation "Cert:\LocalMachine\Root"
# Win+R => mmc
# Validar o certificado
# curl -I https://portainer.mrqz.me
# curl -I https://portainer.mrqz.me --ssl-no-revoke
# curl -vk https://portainer.mrqz.me

# docker compose up -d
# docker compose logs -f nginx
